name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Debug Git environment
        run: |
          git remote -v
          git branch --show-current
          git status --short

      - name: Prepare published folder and write deployed commit SHA
        run: |
          mkdir -p ./www
          echo "${{ github.sha }}" > ./www/deployed_commit.txt

      - name: Deploy `www/` to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
